# Generated by Django 4.0.4 on 2022-06-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_bloguser_id_alter_bloguser_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.bloguser'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.bloguser'),
        ),
    ]
